import turtle
turtle.fillcolor("Black")
turtle.begin_fill()
turtle.pencolor("Red")
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.end_fill()
turtle.done()