import turtle
# turtle.fillcolor("Purple")
# turtle.begin_fill()
# turtle.pencolor("Black")
# turtle.forward(100)
# turtle.right(72)
# turtle.forward(100)
# turtle.right(72)
# turtle.forward(100)
# turtle.right(72)
# turtle.forward(100)
# turtle.end_fill()
# turtle.done()

# turtle.fillcolor("Black")
# turtle.begin_fill()
# turtle.circle(100)
# turtle.end_fill()
# turtle.goto(70,140)
# turtle.fillcolor("Black")
# turtle.begin_fill()
# turtle.circle(50)
# turtle.end_fill()
# turtle.fillcolor("Black")
# turtle.begin_fill()
# turtle.goto(-70,140)
# turtle.circle(50)
# turtle.end_fill()
# turtle.done()

turtle.penup()
turtle.backward(300)
turtle.pendown()
for i in range(2):
    turtle.penup()
    turtle. forward(200)
    turtle.pendown()
    for i in range(2):
        turtle.forward(100)
        turtle.right(90)
        
turtle.done()